/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#f3e24d",
        "on-secondary": "#ffffff",
        "primary-container": "#d4e157",
        surface: "#f4faff",
        "on-tertiary-fixed": "#002105",
        "on-tertiary-fixed-variant": "#005318",
        "on-primary-fixed": "#1a1d00",
        "on-surface-variant": "#474836",
        "surface-container-highest": "#d7e4ec",
        "outline-variant": "#c8c8b1",
        "inverse-primary": "#c2cf47",
        tertiary: "#126d27",
        "on-surface": "#111d23",
        "surface-container-high": "#ddeaf2",
        "surface-container-low": "#e9f6fd",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "inverse-on-surface": "#e6f3fb",
        "on-primary-fixed-variant": "#444b00",
        "surface-variant": "#d7e4ec",
        "surface-tint": "#5b6300",
        "on-tertiary": "#ffffff",
        "surface-dim": "#cfdce4",
        "tertiary-container": "#94ec95",
        "on-tertiary-container": "#116c26",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#d9c935",
        "on-primary-container": "#5b6300",
        primary: "#5b6300",
        "primary-fixed": "#dfec60",
        secondary: "#686000",
        "surface-bright": "#f4faff",
        "primary-fixed-dim": "#c2cf47",
        "on-secondary-fixed-variant": "#4f4800",
        "tertiary-fixed": "#9ff79f",
        "on-secondary-fixed": "#1f1c00",
        "surface-container": "#e3f0f8",
        outline: "#787864",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#263238",
        "secondary-fixed": "#f6e550",
        "on-secondary-container": "#6d6400",
        "on-background": "#111d23",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        background: "#f4faff",
        "tertiary-fixed-dim": "#83da85",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        xl: "80px",
        base: "8px",
        sm: "12px",
        lg: "48px",
        gutter: "24px",
        "margin-desktop": "40px",
        xs: "4px",
        md: "24px",
      },
      fontFamily: {
        "body-lg": ["Work Sans", "sans-serif"],
        "headline-xl": ["Manrope", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "data-table": ["Work Sans", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        "body-sm": ["Work Sans", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "data-table": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
